fix: Remove Cart Items For Online Payment
CODE-73/vestido-ecommerce pull request #122
Opened 2024-09-16 16:25 UTC by mohammedfabinsha

2024-09-18 00:38 UTC, fahimalizain commented
@mohammedfabinsha Can we have a dedicated libs/items/cart/service `clearCartOnOrderCreation(order: Order)`? And use it for both COD & Online?

2024-10-22 02:22 UTC, fahimalizain requested changes
Please update with latest `master` and fix build errors.

2024-11-05 04:19 UTC, mohammedfabinsha commented
> Please update with latest `master` and fix build errors.

Done

2024-11-06 05:14 UTC, fahimalizain approved these changes

2024-11-06 05:14 UTC, merged