fix: Introduced Function calculateTotal
CODE-73/vestido-ecommerce pull request #127
Opened 2024-09-25 07:57 UTC by mohammedfabinsha

2024-10-03 14:13 UTC, fahimalizain requested changes

2024-10-03 14:13 UTC, fahimalizain commented on libs/orders/src/services/orders/calculate-total/zod.ts
> +export const calculateTotalSchema = z.object({
Why this is not capitalized?

2024-10-10 05:59 UTC, mohammedfabinsha commented on libs/orders/src/services/orders/calculate-total/zod.ts
> +export const calculateTotalSchema = z.object({
resolved

2024-10-19 11:36 UTC, fahimalizain approved these changes

2024-10-19 11:36 UTC, merged